/* db.java */
/* Generated By:JavaCC: Do not edit this line. db.java */
package xml.db;
import java.util.ArrayList;
import archivos.*;
import archivos.db.*;
import archivos.metodo.function;
import archivos.metodo.procedure;
import archivos.objeto.object;
import archivos.tabla.fila_tabla;
import archivos.tabla.fila_tabla_objeto;
import archivos.tabla.table;

public class db implements dbConstants {
  private String tipo,nombre,path,contador,nombre_param;
  private String nulo, no_nulo, autoincrementable, llave_primaria, llave_foranea;
  ArrayList<table> lt = new ArrayList<table>();
  private ArrayList<database> ldb= new ArrayList<database>();

  public static void main(String args[]) throws ParseException {
    db parser = new db(System.in);
    parser.S();
  }

  final public ArrayList<database> S() throws ParseException {
    LISTA_REGISTRO();
{if ("" != null) return ldb;}
    throw new Error("Missing return statement in function");
  }

  final public void LISTA_REGISTRO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_PROCEDURE_ABRE:{
      PROCEDURE();
      break;
      }
    case TOKEN_FUNCTION_ABRE:{
      FUNCTION();
      break;
      }
    case TOKEN_OBJECT_ABRE:{
      OBJECT();
      break;
      }
    case TOKEN_TABLE_ABRE:{
      TABLE();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_PROCEDURE_ABRE:
    case TOKEN_OBJECT_ABRE:
    case TOKEN_TABLE_ABRE:
    case TOKEN_FUNCTION_ABRE:{
      LISTA_REGISTRO();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
  }

  final public void PROCEDURE() throws ParseException {Token p;
    jj_consume_token(TOKEN_PROCEDURE_ABRE);
    jj_consume_token(TOKEN_PATH_ABRE);
    p = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_PATH_CIERRA);
    jj_consume_token(TOKEN_PROCEDURE_CIERRA);
path= p.image;
     path= path.substring(1, path.length()-1);
     ArrayList<procedure> proc= new ArrayList<procedure>();
     database data = new database("PROCEDURE",null,path,null,proc,null,null,0);
     ldb.add(data);
  }

  final public void FUNCTION() throws ParseException {Token p;
    jj_consume_token(TOKEN_FUNCTION_ABRE);
    jj_consume_token(TOKEN_PATH_ABRE);
    p = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_PATH_CIERRA);
    jj_consume_token(TOKEN_FUNCTION_CIERRA);
path= p.image;
     path= path.substring(1, path.length()-1);
     ArrayList<function> func = new ArrayList<function>();
     database data = new database("FUNCTION",null,path,func,null,null,null,0);
     ldb.add(data);
  }

  final public void OBJECT() throws ParseException {Token p;
    jj_consume_token(TOKEN_OBJECT_ABRE);
    jj_consume_token(TOKEN_PATH_ABRE);
    p = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_PATH_CIERRA);
    jj_consume_token(TOKEN_OBJECT_CIERRA);
path= p.image;
     path= path.substring(1, path.length()-1);
     ArrayList<object> obj = new ArrayList<object>();
     database data = new database("OBJECT",null,path,null,null,obj,null,0);
     ldb.add(data);
  }

  final public void TABLE() throws ParseException {Token n,p,c;
    jj_consume_token(TOKEN_TABLE_ABRE);
    jj_consume_token(TOKEN_NOMBRE_ABRE);
    n = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_NOMBRE_CIERRA);
    jj_consume_token(TOKEN_PATH_ABRE);
    p = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_PATH_CIERRA);
    jj_consume_token(TOKEN_CONTADOR_ABRE);
    c = jj_consume_token(CADENA);
    jj_consume_token(TOKEN_CONTADOR_CIERRA);
    jj_consume_token(TOKEN_ROWS_ABRE);
    LISTA_TIPO();
    jj_consume_token(TOKEN_ROWS_CIERRA);
    jj_consume_token(TOKEN_TABLE_CIERRA);
nombre= n.image;
        nombre= nombre.substring(1, nombre.length()-1);
        path= p.image;
        path= path.substring(1, path.length()-1);
        contador= c.image;
        contador= contador.substring(1, contador.length()-1);
        int cont= Integer.parseInt(contador);
        database data = new database("TABLE",nombre,path,null,null,null,lt,cont);
        ldb.add(data);
        lt = new ArrayList<table>();
  }

  final public void LISTA_TIPO() throws ParseException {
    jj_consume_token(TOKEN_FIELD_ABRE);
    TIPO();
    jj_consume_token(TOKEN_FIELD_CIERRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_FIELD_ABRE:{
      LISTA_TIPO();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
  }

  final public void TIPO() throws ParseException {Token t,tip,f;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INTEGER_ABRE:{
      jj_consume_token(TOKEN_INTEGER_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_INTEGER_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"ENTERO",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_TEXT_ABRE:{
      jj_consume_token(TOKEN_TEXT_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_TEXT_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"CADENA",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_DOUBLE_ABRE:{
      jj_consume_token(TOKEN_DOUBLE_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_DOUBLE_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"DOUBLE",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_BOOL_ABRE:{
      jj_consume_token(TOKEN_BOOL_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_BOOL_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"BOOL",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_DATE_ABRE:{
      jj_consume_token(TOKEN_DATE_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_DATE_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"DATE",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_DATETIME_ABRE:{
      jj_consume_token(TOKEN_DATETIME_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_DATETIME_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla> registro = new ArrayList<fila_tabla>();
                                                                table ta= new table(nombre_param,"DATETIME",nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,registro,false,null);
                                                                lt.add(ta);
      break;
      }
    case TOKEN_ID_ABRE:{
      tip = jj_consume_token(TOKEN_ID_ABRE);
      t = jj_consume_token(CADENA);
      jj_consume_token(TOKEN_ID_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_ABRE);
      jj_consume_token(TOKEN_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
nulo="N";
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NULO_CIERRA);
      jj_consume_token(TOKEN_NO_NULO_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
no_nulo="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
no_nulo="N";
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_NO_NULO_CIERRA);
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
autoincrementable="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
autoincrementable="N";
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_AUTOINCREMENTABLE_CIERRA);
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_Y:{
        jj_consume_token(TOKEN_Y);
llave_primaria="Y";
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_primaria="N";
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_PRIMARIA_CIERRA);
      jj_consume_token(TOKEN_LLAVE_FORANEA_ABRE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CADENA:{
        f = jj_consume_token(CADENA);
llave_foranea= f.image;
                                                                                                                llave_foranea= llave_foranea.substring(1, llave_foranea.length()-1);
        break;
        }
      case TOKEN_N:{
        jj_consume_token(TOKEN_N);
llave_foranea="N";
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(TOKEN_LLAVE_FORANEA_CIERRA);
      jj_consume_token(TOKEN_PROPERTY_CIERRA);
tipo = tip.image;
                                                                tipo = tipo.substring(1, tipo.length()-1);
                                                                nombre_param= t.image;
                                                                nombre_param= nombre_param.substring(1, nombre_param.length()-1);
                                                                ArrayList<fila_tabla_objeto> registro_objeto = new ArrayList<fila_tabla_objeto>();
                                                                table ta= new table(nombre_param,tipo,nulo,no_nulo,autoincrementable,llave_primaria,llave_foranea,null,true,registro_objeto);
                                                                lt.add(ta);
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public dbTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[39];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2800082,0x2800082,0x8000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2aa800,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x1800,0x1800,0x1800,0x1800,0x9000,0x2000,};
   }

  /** Constructor with InputStream. */
  public db(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public db(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new dbTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public db(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new dbTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public db(dbTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(dbTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 39; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
