/* Generated By:JavaCC: Do not edit this line. dbConstants.java */
package xml.db;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface dbConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_PROCEDURE_ABRE = 1;
  /** RegularExpression Id. */
  int TOKEN_PROCEDURE_CIERRA = 2;
  /** RegularExpression Id. */
  int TOKEN_PATH_ABRE = 3;
  /** RegularExpression Id. */
  int TOKEN_PATH_CIERRA = 4;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_ABRE = 5;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_CIERRA = 6;
  /** RegularExpression Id. */
  int TOKEN_OBJECT_ABRE = 7;
  /** RegularExpression Id. */
  int TOKEN_OBJECT_CIERRA = 8;
  /** RegularExpression Id. */
  int TOKEN_ROWS_ABRE = 9;
  /** RegularExpression Id. */
  int TOKEN_ROWS_CIERRA = 10;
  /** RegularExpression Id. */
  int TOKEN_TEXT_ABRE = 11;
  /** RegularExpression Id. */
  int TOKEN_TEXT_CIERRA = 12;
  /** RegularExpression Id. */
  int TOKEN_INTEGER_ABRE = 13;
  /** RegularExpression Id. */
  int TOKEN_INTEGER_CIERRA = 14;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE_ABRE = 15;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE_CIERRA = 16;
  /** RegularExpression Id. */
  int TOKEN_BOOL_ABRE = 17;
  /** RegularExpression Id. */
  int TOKEN_BOOL_CIERRA = 18;
  /** RegularExpression Id. */
  int TOKEN_DATE_ABRE = 19;
  /** RegularExpression Id. */
  int TOKEN_DATE_CIERRA = 20;
  /** RegularExpression Id. */
  int TOKEN_DATETIME_ABRE = 21;
  /** RegularExpression Id. */
  int TOKEN_DATETIME_CIERRA = 22;
  /** RegularExpression Id. */
  int TOKEN_TABLE_ABRE = 23;
  /** RegularExpression Id. */
  int TOKEN_TABLE_CIERRA = 24;
  /** RegularExpression Id. */
  int TOKEN_FUNCTION_ABRE = 25;
  /** RegularExpression Id. */
  int TOKEN_FUNCTION_CIERRA = 26;
  /** RegularExpression Id. */
  int TOKEN_FIELD_ABRE = 27;
  /** RegularExpression Id. */
  int TOKEN_FIELD_CIERRA = 28;
  /** RegularExpression Id. */
  int TOKEN_PROPERTY_ABRE = 29;
  /** RegularExpression Id. */
  int TOKEN_PROPERTY_CIERRA = 30;
  /** RegularExpression Id. */
  int TOKEN_NULO_ABRE = 31;
  /** RegularExpression Id. */
  int TOKEN_NULO_CIERRA = 32;
  /** RegularExpression Id. */
  int TOKEN_NO_NULO_ABRE = 33;
  /** RegularExpression Id. */
  int TOKEN_NO_NULO_CIERRA = 34;
  /** RegularExpression Id. */
  int TOKEN_AUTOINCREMENTABLE_ABRE = 35;
  /** RegularExpression Id. */
  int TOKEN_AUTOINCREMENTABLE_CIERRA = 36;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_PRIMARIA_ABRE = 37;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_PRIMARIA_CIERRA = 38;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_FORANEA_ABRE = 39;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_FORANEA_CIERRA = 40;
  /** RegularExpression Id. */
  int TOKEN_CONTADOR_ABRE = 41;
  /** RegularExpression Id. */
  int TOKEN_CONTADOR_CIERRA = 42;
  /** RegularExpression Id. */
  int TOKEN_Y = 43;
  /** RegularExpression Id. */
  int TOKEN_N = 44;
  /** RegularExpression Id. */
  int TOKEN_ID_ABRE = 45;
  /** RegularExpression Id. */
  int TOKEN_ID_CIERRA = 46;
  /** RegularExpression Id. */
  int CADENA = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<procedure>\"",
    "\"</procedure>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<object>\"",
    "\"</object>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<cadena>\"",
    "\"</cadena>\"",
    "\"<entero>\"",
    "\"</entero>\"",
    "\"<double>\"",
    "\"</double>\"",
    "\"<bool>\"",
    "\"</bool>\"",
    "\"<date>\"",
    "\"</date>\"",
    "\"<datetime>\"",
    "\"</datetime>\"",
    "\"<table>\"",
    "\"</table>\"",
    "\"<function>\"",
    "\"</function>\"",
    "\"<field>\"",
    "\"</field>\"",
    "\"<property>\"",
    "\"</property>\"",
    "\"<nulo>\"",
    "\"</nulo>\"",
    "\"<no_nulo>\"",
    "\"</no_nulo>\"",
    "\"<autoincrementable>\"",
    "\"</autoincrementable>\"",
    "\"<llave_primaria>\"",
    "\"</llave_primaria>\"",
    "\"<llave_foranea>\"",
    "\"</llave_foranea>\"",
    "\"<contador>\"",
    "\"</contador>\"",
    "<TOKEN_Y>",
    "<TOKEN_N>",
    "<TOKEN_ID_ABRE>",
    "<TOKEN_ID_CIERRA>",
    "<CADENA>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
