/* paquete.java */
/* Generated By:JavaCC: Do not edit this line. paquete.java */
package paquetes;
import  archivos.memoria;


public class paquete implements paqueteConstants {
  public static void main(String args[]) throws ParseException {
    paquete parser = new paquete(System.in);
  }

  final public void S() throws ParseException {
    E();
  }

  final public void E() throws ParseException {
    jj_consume_token(COR_ABRE);
    jj_consume_token(TOKEN_VALIDAR);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(CADENA);
    jj_consume_token(COMA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_LOGIN:{
      VALIDAR();
      break;
      }
    case TOKEN_PAQUETE:{
      PAQUETE();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(COR_CIERRA);
  }

  final public void VALIDAR() throws ParseException {String usr, pass;
Token u, p;
    jj_consume_token(TOKEN_LOGIN);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(COR_ABRE);
    jj_consume_token(TOKEN_USR);
    jj_consume_token(DOSPUNTOS);
    u = jj_consume_token(CADENA);
    jj_consume_token(COMA);
    jj_consume_token(TOKEN_PASS);
    jj_consume_token(DOSPUNTOS);
    p = jj_consume_token(CADENA);
    jj_consume_token(COR_CIERRA);
memoria.paquetePly="LOGIN";
    usr = u.image;
    usr = usr.substring(1, usr.length()-1);
    memoria.usrPly= usr;

    pass = p.image;
    pass = pass.substring(1, pass.length()-1);
    memoria.passPly= pass;
  }

  final public void PAQUETE() throws ParseException {Token t;
String cod;
    jj_consume_token(TOKEN_PAQUETE);
    jj_consume_token(DOSPUNTOS);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_FIN:{
      jj_consume_token(TOKEN_FIN);
memoria.paquetePly="FIN";
      break;
      }
    case TOKEN_USQL:
    case TOKEN_REPORTE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_USQL:{
        jj_consume_token(TOKEN_USQL);
memoria.paquetePly="USQL";
        break;
        }
      case TOKEN_REPORTE:{
        jj_consume_token(TOKEN_REPORTE);
memoria.paquetePly="REPORTE";
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COMA);
      jj_consume_token(TOKEN_INSTRUCCION);
      jj_consume_token(DOSPUNTOS);
      t = jj_consume_token(CODIGO);
cod = t.image;
                                                cod = cod.substring(1, cod.length()-1);
                                                memoria.codigoPly = cod;
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public paqueteTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc0,0x1800,0x1c00,};
   }

  /** Constructor with InputStream. */
  public paquete(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public paquete(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new paqueteTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public paquete(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new paqueteTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public paquete(paqueteTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(paqueteTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[22];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 22; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
