/* Generated By:JavaCC: Do not edit this line. paqueteConstants.java */
package paquetes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface paqueteConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COR_ABRE = 1;
  /** RegularExpression Id. */
  int COR_CIERRA = 2;
  /** RegularExpression Id. */
  int COMA = 3;
  /** RegularExpression Id. */
  int DOSPUNTOS = 4;
  /** RegularExpression Id. */
  int TOKEN_VALIDAR = 5;
  /** RegularExpression Id. */
  int TOKEN_PAQUETE = 6;
  /** RegularExpression Id. */
  int TOKEN_LOGIN = 7;
  /** RegularExpression Id. */
  int TOKEN_COMANDO = 8;
  /** RegularExpression Id. */
  int TOKEN_INSTRUCCION = 9;
  /** RegularExpression Id. */
  int TOKEN_FIN = 10;
  /** RegularExpression Id. */
  int TOKEN_USQL = 11;
  /** RegularExpression Id. */
  int TOKEN_REPORTE = 12;
  /** RegularExpression Id. */
  int TOKEN_ARBOL = 13;
  /** RegularExpression Id. */
  int TOKEN_USR = 14;
  /** RegularExpression Id. */
  int TOKEN_PASS = 15;
  /** RegularExpression Id. */
  int CODIGO = 16;
  /** RegularExpression Id. */
  int CADENA = 17;
  /** RegularExpression Id. */
  int ENTERO = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "<TOKEN_VALIDAR>",
    "<TOKEN_PAQUETE>",
    "<TOKEN_LOGIN>",
    "<TOKEN_COMANDO>",
    "<TOKEN_INSTRUCCION>",
    "<TOKEN_FIN>",
    "<TOKEN_USQL>",
    "<TOKEN_REPORTE>",
    "<TOKEN_ARBOL>",
    "<TOKEN_USR>",
    "<TOKEN_PASS>",
    "<CODIGO>",
    "<CADENA>",
    "<ENTERO>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
