/* Generated By:JavaCC: Do not edit this line. analizadorConstants.java */
package analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface analizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAR_ABRE = 1;
  /** RegularExpression Id. */
  int PAR_CIERRA = 2;
  /** RegularExpression Id. */
  int LLAVE_ABRE = 3;
  /** RegularExpression Id. */
  int LLAVE_CIERRA = 4;
  /** RegularExpression Id. */
  int PYCOMA = 5;
  /** RegularExpression Id. */
  int COMA = 6;
  /** RegularExpression Id. */
  int DOSPUNTOS = 7;
  /** RegularExpression Id. */
  int IGUAL = 8;
  /** RegularExpression Id. */
  int PUNTO = 9;
  /** RegularExpression Id. */
  int MAS = 10;
  /** RegularExpression Id. */
  int MENOS = 11;
  /** RegularExpression Id. */
  int POR = 12;
  /** RegularExpression Id. */
  int DIVISION = 13;
  /** RegularExpression Id. */
  int POTENCIA = 14;
  /** RegularExpression Id. */
  int AUMENTO = 15;
  /** RegularExpression Id. */
  int DECREMENTO = 16;
  /** RegularExpression Id. */
  int IGUALACION = 17;
  /** RegularExpression Id. */
  int DIFERENTE = 18;
  /** RegularExpression Id. */
  int MENOR = 19;
  /** RegularExpression Id. */
  int MAYOR = 20;
  /** RegularExpression Id. */
  int MENORIGUAL = 21;
  /** RegularExpression Id. */
  int MAYORIGUAL = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int MENOR_2 = 26;
  /** RegularExpression Id. */
  int MAYOR_2 = 27;
  /** RegularExpression Id. */
  int TOKEN_CREAR = 28;
  /** RegularExpression Id. */
  int TOKEN_BASE_DATOS = 29;
  /** RegularExpression Id. */
  int TOKEN_TABLA = 30;
  /** RegularExpression Id. */
  int TOKEN_NULO = 31;
  /** RegularExpression Id. */
  int TOKEN_NO_NULO = 32;
  /** RegularExpression Id. */
  int TOKEN_AUTOINCREMETABLE = 33;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_PRIMARIA = 34;
  /** RegularExpression Id. */
  int TOKEN_LLAVE_FORANEA = 35;
  /** RegularExpression Id. */
  int TOKEN_OBJETO = 36;
  /** RegularExpression Id. */
  int TOKEN_PROCEDIMIENTO = 37;
  /** RegularExpression Id. */
  int TOKEN_FUNCION = 38;
  /** RegularExpression Id. */
  int TOKEN_RETORNO = 39;
  /** RegularExpression Id. */
  int TOKEN_USUARIO = 40;
  /** RegularExpression Id. */
  int TOKEN_COLOCAR = 41;
  /** RegularExpression Id. */
  int TOKEN_PASSWORD = 42;
  /** RegularExpression Id. */
  int TOKEN_USAR = 43;
  /** RegularExpression Id. */
  int TOKEN_ALTERAR = 44;
  /** RegularExpression Id. */
  int TOKEN_AGREGAR = 45;
  /** RegularExpression Id. */
  int TOKEN_QUITAR = 46;
  /** RegularExpression Id. */
  int TOKEN_CAMBIAR = 47;
  /** RegularExpression Id. */
  int TOKEN_ELIMINAR = 48;
  /** RegularExpression Id. */
  int TOKEN_INSERTAR = 49;
  /** RegularExpression Id. */
  int TOKEN_VALORES = 50;
  /** RegularExpression Id. */
  int TOKEN_ACTUALIZAR = 51;
  /** RegularExpression Id. */
  int TOKEN_DONDE = 52;
  /** RegularExpression Id. */
  int TOKEN_BORRAR = 53;
  /** RegularExpression Id. */
  int TOKEN_SELECCIONAR = 54;
  /** RegularExpression Id. */
  int TOKEN_DE = 55;
  /** RegularExpression Id. */
  int TOKEN_ORDENAR = 56;
  /** RegularExpression Id. */
  int TOKEN_ASC = 57;
  /** RegularExpression Id. */
  int TOKEN_DESC = 58;
  /** RegularExpression Id. */
  int TOKEN_OTORGAR = 59;
  /** RegularExpression Id. */
  int TOKEN_DENEGAR = 60;
  /** RegularExpression Id. */
  int TOKEN_DECLARAR = 61;
  /** RegularExpression Id. */
  int TOKEN_SI = 62;
  /** RegularExpression Id. */
  int TOKEN_SINO = 63;
  /** RegularExpression Id. */
  int TOKEN_SELECCIONA = 64;
  /** RegularExpression Id. */
  int TOKEN_CASO = 65;
  /** RegularExpression Id. */
  int TOKEN_DEFECTO = 66;
  /** RegularExpression Id. */
  int TOKEN_PARA = 67;
  /** RegularExpression Id. */
  int TOKEN_MIENTRAS = 68;
  /** RegularExpression Id. */
  int TOKEN_DETENER = 69;
  /** RegularExpression Id. */
  int TOKEN_IMPRIMIR = 70;
  /** RegularExpression Id. */
  int TOKEN_FECHA = 71;
  /** RegularExpression Id. */
  int TOKEN_FECHA_HORA = 72;
  /** RegularExpression Id. */
  int TOKEN_CONTAR = 73;
  /** RegularExpression Id. */
  int TOKEN_BACKUP_USQL = 74;
  /** RegularExpression Id. */
  int TOKEN_BACKUP_COMPLETO = 75;
  /** RegularExpression Id. */
  int TOKEN_RESTAURAR_USQL = 76;
  /** RegularExpression Id. */
  int TOKEN_RESTAURAR_COMPLETO = 77;
  /** RegularExpression Id. */
  int TOKEN_TEXT = 78;
  /** RegularExpression Id. */
  int TOKEN_INTEGER = 79;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE = 80;
  /** RegularExpression Id. */
  int TOKEN_BOOL = 81;
  /** RegularExpression Id. */
  int TOKEN_DATE = 82;
  /** RegularExpression Id. */
  int TOKEN_DATETIME = 83;
  /** RegularExpression Id. */
  int CADENA = 84;
  /** RegularExpression Id. */
  int ENTERO = 85;
  /** RegularExpression Id. */
  int NUMERO = 86;
  /** RegularExpression Id. */
  int DECIMAL = 87;
  /** RegularExpression Id. */
  int ID = 88;
  /** RegularExpression Id. */
  int VARIABLE = 89;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 94;
  /** RegularExpression Id. */
  int COMENTARIO_MULTI = 95;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"=\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"<<\"",
    "\">>\"",
    "\"crear\"",
    "\"base_datos\"",
    "\"tabla\"",
    "\"nulo\"",
    "\"no nulo\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "\"llave_foranea\"",
    "\"objeto\"",
    "\"procedimiento\"",
    "\"funcion\"",
    "\"retorno\"",
    "\"usuario\"",
    "\"colocar\"",
    "\"password\"",
    "\"usar\"",
    "\"alterar\"",
    "\"agregar\"",
    "\"quitar\"",
    "\"cambiar\"",
    "\"eliminar\"",
    "\"insertar en\"",
    "\"valores\"",
    "\"actualizar\"",
    "\"donde\"",
    "\"borrar en\"",
    "\"seleccionar\"",
    "\"de\"",
    "\"ordenar por\"",
    "\"asc\"",
    "\"desc\"",
    "\"otorgar permisos\"",
    "\"denegar permisos\"",
    "\"declarar\"",
    "\"si\"",
    "\"sino\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"defecto\"",
    "\"para\"",
    "\"mientras\"",
    "\"detener\"",
    "\"imprimir\"",
    "\"fecha\"",
    "\"fecha_hora\"",
    "\"contar\"",
    "\"backup usqldump\"",
    "\"backup completo\"",
    "\"restaurar usqldump\"",
    "\"restaurar completo\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"datetime\"",
    "<CADENA>",
    "<ENTERO>",
    "<NUMERO>",
    "<DECIMAL>",
    "<ID>",
    "<VARIABLE>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_MULTI>",
  };

}
