/* Generated By:JavaCC: Do not edit this line. usuarioConstants.java */
package xml.usuario;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface usuarioConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_USR_ABRE = 1;
  /** RegularExpression Id. */
  int TOKEN_USR_CIERRA = 2;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_ABRE = 3;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_CIERRA = 4;
  /** RegularExpression Id. */
  int TOKEN_PASS_ABRE = 5;
  /** RegularExpression Id. */
  int TOKEN_PASS_CIERRA = 6;
  /** RegularExpression Id. */
  int TOKEN_TIPO_ABRE = 7;
  /** RegularExpression Id. */
  int TOKEN_TIPO_CIERRA = 8;
  /** RegularExpression Id. */
  int TOKEN_ESTADO_ABRE = 9;
  /** RegularExpression Id. */
  int TOKEN_ESTADO_CIERRA = 10;
  /** RegularExpression Id. */
  int TOKEN_PERMISO_ABRE = 11;
  /** RegularExpression Id. */
  int TOKEN_PERMISO_CIERRA = 12;
  /** RegularExpression Id. */
  int TOKEN_DB_ABRE = 13;
  /** RegularExpression Id. */
  int TOKEN_DB_CIERRA = 14;
  /** RegularExpression Id. */
  int TOKEN_TABLA_ABRE = 15;
  /** RegularExpression Id. */
  int TOKEN_TABLA_CIERRA = 16;
  /** RegularExpression Id. */
  int TOKEN_OBJ_ABRE = 17;
  /** RegularExpression Id. */
  int TOKEN_OBJ_CIERRA = 18;
  /** RegularExpression Id. */
  int TOKEN_FUNC_ABRE = 19;
  /** RegularExpression Id. */
  int TOKEN_FUNC_CIERRA = 20;
  /** RegularExpression Id. */
  int TOKEN_PROC_ABRE = 21;
  /** RegularExpression Id. */
  int TOKEN_PROC_CIERRA = 22;
  /** RegularExpression Id. */
  int CADENA = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<usr>\"",
    "\"</usr>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<pass>\"",
    "\"</pass>\"",
    "\"<tipo>\"",
    "\"</tipo>\"",
    "\"<estado>\"",
    "\"</estado>\"",
    "\"<permiso>\"",
    "\"</permiso>\"",
    "\"<db>\"",
    "\"</db>\"",
    "\"<tabla>\"",
    "\"</tabla>\"",
    "\"<obj>\"",
    "\"</obj>\"",
    "\"<func>\"",
    "\"</func>\"",
    "\"<proc>\"",
    "\"</proc>\"",
    "<CADENA>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
