/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consola;

import DDL.alter;
import DDL.create;
import DDL.eliminar;
import archivos.LecturaBD;
import archivos.maestro.master;
import archivos.memoria;
import archivos.parametro;
import archivos.tabla.table;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import socket.server;
import usql.analizador;
import xml.usuario.usuario;

/**
 *
 * @author anick
 */
public class principal extends javax.swing.JFrame {

    ArrayList<parametro> lp = new ArrayList<parametro>();
    ArrayList<parametro> lpalter = new ArrayList<parametro>();
    ArrayList<parametro> lpalter_quitar = new ArrayList<parametro>();
    ArrayList<parametro> lpalter_quitar_columna = new ArrayList<parametro>();

    ArrayList<table> lt = new ArrayList<table>();
    ArrayList<table> lt2 = new ArrayList<table>();
    //create cre = new create();
    //alter alt = new alter();
    //eliminar eli = new eliminar();

    Thread server = new Thread(new server(), "server");

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        socket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText(">>");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void socket() {
        server.start();

        try {
            Thread.currentThread().sleep(1000);
        } catch (InterruptedException e) {
        }
    }

    private void pruebaUSQL() {
        analizador g = new analizador(new java.io.StringReader(this.jTextArea1.getText()));
        try {
            g.S().ejecucion();
        } catch (usql.ParseException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void imprimir(String Mensaje) {
        jTextArea1.setText(jTextArea1.getText() + "\n >>" + Mensaje);
    }
    
    public static String getText(){
        return jTextArea1.getText();
    }

    //Probar gramatica
    private void testUsuario() {
        usuario g = new usuario(new java.io.StringReader(this.jTextArea1.getText()));
        try {
            g.S();
            System.out.print("Exito");
        } catch (xml.usuario.ParseException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
