/* Generated By:JavaCC: Do not edit this line. objetoConstants.java */
package xml.objeto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface objetoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_OBJ_ABRE = 1;
  /** RegularExpression Id. */
  int TOKEN_OBJ_CIERRA = 2;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_ABRE = 3;
  /** RegularExpression Id. */
  int TOKEN_NOMBRE_CIERRA = 4;
  /** RegularExpression Id. */
  int TOKEN_ATTR_ABRE = 5;
  /** RegularExpression Id. */
  int TOKEN_ATTR_CIERRA = 6;
  /** RegularExpression Id. */
  int TOKEN_TEXT_ABRE = 7;
  /** RegularExpression Id. */
  int TOKEN_TEXT_CIERRA = 8;
  /** RegularExpression Id. */
  int TOKEN_INTEGER_ABRE = 9;
  /** RegularExpression Id. */
  int TOKEN_INTEGER_CIERRA = 10;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE_ABRE = 11;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE_CIERRA = 12;
  /** RegularExpression Id. */
  int TOKEN_BOOL_ABRE = 13;
  /** RegularExpression Id. */
  int TOKEN_BOOL_CIERRA = 14;
  /** RegularExpression Id. */
  int TOKEN_DATE_ABRE = 15;
  /** RegularExpression Id. */
  int TOKEN_DATE_CIERRA = 16;
  /** RegularExpression Id. */
  int TOKEN_DATETIME_ABRE = 17;
  /** RegularExpression Id. */
  int TOKEN_DATETIME_CIERRA = 18;
  /** RegularExpression Id. */
  int TOKEN_ID_ABRE = 19;
  /** RegularExpression Id. */
  int TOKEN_ID_CIERRA = 20;
  /** RegularExpression Id. */
  int CADENA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<obj>\"",
    "\"</obj>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"<cadena>\"",
    "\"</cadena>\"",
    "\"<entero>\"",
    "\"</entero>\"",
    "\"<double>\"",
    "\"</double>\"",
    "\"<bool>\"",
    "\"</bool>\"",
    "\"<date>\"",
    "\"</date>\"",
    "\"<datetime>\"",
    "\"</datetime>\"",
    "<TOKEN_ID_ABRE>",
    "<TOKEN_ID_CIERRA>",
    "<CADENA>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
